<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Player;

class PlayerSeeder extends Seeder
{
    public function run(): void
    {
        $yaroslavichPlayers = [
            [
                'full_name' => 'Созонов Юрий',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Тихонов Ярослав',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Шведов Константин',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Паутов Александр',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Сарычев Никита',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ященин Савелий',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Красильников Георгий',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Вельс Григорий',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Клемин Владимир',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Чумаков Архип',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Товстый Александр',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Зашивалов Даниил',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Нежданов Игорь',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Золотов Тихан',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Шилов Никита',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Афанасьев Артем',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Левченко Владислав',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Федотов Георгий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Воронин Тимофей',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Смирнов Илья',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Зубов Матвей',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Божедомов Михаил',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        $torpedoPlayers = [
            [
                'full_name' => 'Чеблоков Даниил',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Тихонов Антон',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Тумаков Иван',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Пеньков Никита',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Казаков Даниил',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Зазнобин Егор',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Челин Павел',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Голубев Владимир',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Иванов Тихон',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кравчук Егор',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Белавский Дмитрий',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ткаченко Никита',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Крюков Даниил',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Марков Андрей',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Морозов Иван',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Медведев Георгий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Шушин Даниил',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Шлыков Егор',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Седов Егор',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Железняков Мирослав',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Камушков Клим',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Савченко Павел',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Заблоцкий Евгений',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Тельман Евгений',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Чванчиков Андрей',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кустов Даниил',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Орлов Илья',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кулешов Владислав',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Воробьев Владислав',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Малетин Илья',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        $pereslavlPlayers = [
            [
                'full_name' => 'Безменов Егор',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Шиляев Даниил',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Киселев Никита',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Королев Александр',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Комаров Максим',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Морин Илья',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Выдряков Роман',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Козлов Михаил',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Мельников Андрей',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Гречухин Александр',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Гусев Матвей',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ларионов Павел ст.',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ларионов Павел мл.',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Смирнов Максим',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Прокопенко Ярослав',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Авагян Ашот',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Гуров Александр',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Савельев Никита',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Выдряков Вячеслав',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Жуков Никита',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кузнецов Дмитрий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Хисамутдинов Роман',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Цепков Максим',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Мокшанцев Александр',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Банников Матвей',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Киселев Владислав',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Сударев Кирилл',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        $zubrPlayers = [
            [
                'full_name' => 'Бархаткин Артем',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Щербаков Максим',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Пасынков Александр',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Никулин Семен',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Павлов Леонид',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Собенин Даниил',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кривенко Даниил',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кошелев Александр',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Сон Александр',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ардашев Дмитрий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ардашев Кирилл',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Сорокин Артем',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ершов Иван',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Данилов Иван',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Бондырев Игорь',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кривенко Артем',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Веселовский Роман',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ахметов Тимур',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Стручинский Виктор',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ухарский Андрей',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Пасечник Никита',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Величко Глеб',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кузнецов Даниил',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        $vympelVPlayers = [
            [
                'full_name' => 'Шарпанов Виктор',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Бардин Даниил',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Кокарев Александр',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Пульников Илья',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Грибков Илья',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Фролов Матвей',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Петров Илья',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Лебедев Александр',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Лысых Илья',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Лямин Семен',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Белоусов Анатолий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Бычков Егор',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Волохов Александр',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Игнатьев Кирилл',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Сагимбаев Мерген',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Смирнов Даниил',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Тельцов Иван',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Тимофеев Дмитрий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Уткин Дмитрий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Шайтанов Александр',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        $bgvPlayers = [
            [
                'full_name' => 'Тимошенко Алексей',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Лемеза Вадим',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Канаев Даниил',
                'birth_date' => null,
                'position' => 'вратарь',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Мосолов Николай',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ларюхин Владислав',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Туркин Владислав',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Тонков Никита',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Пушков Павел',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Григоренко Ярослав',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Еремычев Матвей',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Слободянюк Максим',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Антипов Никита',
                'birth_date' => null,
                'position' => 'защитник',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Лисенчук Денис',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Шопыгин Даниил',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Зарубин Денис',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Разживин Артем',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Соколов Илья',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Голосов Егор',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Новиков Антон',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Васильев Максим',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Лавров Дмитрий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Филиппов Илья',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Любимов Никита',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Устинов Даниил',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Шмелев Валерий',
                'birth_date' => null,
                'position' => 'нападающий',
                'grip' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        foreach ($yaroslavichPlayers as $player) {
            Player::create($player);
        }
        echo "\n✅ Игроки команда Ярославич заполнены.\n\n";

        foreach ($torpedoPlayers as $player) {
            Player::create($player);
        }
        echo "✅ Игроки команда Торпедо заполнены.\n\n";

        foreach ($pereslavlPlayers as $player) {
            Player::create($player);
        }
        echo "✅ Игроки команда Переславль заполнены.\n\n";

        foreach ($zubrPlayers as $player) {
            Player::create($player);
        }
        echo "✅ Игроки команда Зубр заполнены.\n\n";

        foreach ($vympelVPlayers as $player) {
            Player::create($player);
        }
        echo "✅ Игроки команда Вымпел-V заполнены.\n\n";

        foreach ($bgvPlayers as $player) {
            Player::create($player);
        }
        echo "✅ Игроки команда БГВ заполнены.\n\n";
    }
}