<?php

namespace Database\Seeders;

use App\Models\Game;
use App\Models\Player;
use App\Models\Team;
use App\Models\Championship;
use App\Models\ChampionshipGame;
use App\Models\ChampionshipPlayer;
use App\Models\ChampionshipTeam;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ZvezdaOtechestvaSeeder extends Seeder
{
    public function run(): void
    {
        $zo = Championship::where('name', 'Звезда Отечества')->first()->id;

        $pereslavl = Team::where('name', 'СХК Переславль-Залесский')->first()->id;
        $zubr = Team::where('name', 'ХК Зубр')->first()->id;
        $vympelV = Team::where('name', 'ХК Вымпел-V')->first()->id;
        $yaroslavich = Team::where('name', 'ХК Ярославич')->first()->id;
        $torpedo = Team::where('name', 'ХК Торпедо')->first()->id;  
        $pvo = Team::where('name', 'ХК ПВО')->first()->id;
        $vremyaZvezd = Team::where('name','ХК Время Звезд')->first()->id;

        $championshipGames = [
            [
                'championship_id' => $zo,
                'game_id' => Game::where('team_a_id', $yaroslavich)
                    ->where('team_b_id', $torpedo)
                    ->where('date', '2025-10-21')
                    ->first()->id,
            ],
            [
                'championship_id' => $zo,
                'game_id' => Game::where('team_a_id', $zubr)
                    ->where('team_b_id', $pvo)
                    ->where('date', '2025-10-22')
                    ->first()->id,
            ],
            [
                'championship_id' => $zo,
                'game_id' => Game::where('team_a_id', $vympelV)
                    ->where('team_b_id', $pereslavl)
                    ->where('date', '2025-10-24')
                    ->first()->id,
            ],
            [
                'championship_id' => $zo,
                'game_id' => Game::where('team_a_id', $yaroslavich)
                    ->where('team_b_id', $zubr)
                    ->where('date', '2025-10-28')
                    ->first()->id,
            ],
            [
                'championship_id' => $zo,
                'game_id' => Game::where('team_a_id', $vympelV)
                    ->where('team_b_id', $pvo)
                    ->where('date', '2025-10-29')
                    ->first()->id,
            ],
        ];

        $teams = [
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $vympelV,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $yaroslavich,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $torpedo,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pvo,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $vremyaZvezd,
            ]
        ];

        $pereslavlPlayers = [
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Безменов Егор')->first()->id,
                'number' => null,

            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Шиляев Даниил')->first()->id,
                'number' => null,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Киселев Никита')->first()->id,
                'number' => null,
            ],
            //----------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Королев Александр')->first()->id,
                'number' => null,
                'gaa' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Комаров Максим')->first()->id,
                'number' => null,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Морин Илья')->first()->id,
                'number' => null,
                'goals' => 0,
                'penalties' => 0,
                'matches' => 0,
                'assists' => 0,
            ],
            //----------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Выдряков Роман')->first()->id,
                'number' => null,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
                'assists' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Козлов Михаил')->first()->id,
                'number' => null,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Мельников Андрей')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            //----------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Гречухин Александр')->first()->id,
                'number' => null,
                'number' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Гусев Матвей')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Ларионов Павел ст.')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            //----------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Ларионов Павел мл.')->first()->id,
                'number' => null,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Смирнов Михаил')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Прокопенко Ярослав')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            //----------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Авагян Ашот')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Гуров Александр')->first()->id,
                'number' => null,
                'goals' => 0,
                'number' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Савельев Никита')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            //----------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Выдряков Вячеслав')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Жуков Никита')->first()->id,
                'number' => null,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Кузнецов Дмитрий')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            //----------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Хисамутдинов Роман')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Цепков Максим')->first()->id,
                'number' => null,
                'goals' => 0,
                'number' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Мокшанцев Александр')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            //----------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Банников Матвей')->first()->id,
                'number' => null,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Киселев Владислав')->first()->id,
                'number' => null,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $pereslavl,
                'player_id' => Player::where('full_name', 'Сударев Кирилл')->first()->id,
                'number' => null,
            ],
        ];

        $zubrPlayers = [
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Бархаткин Артем')->first()->id,
                'number' => null,
                'number' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Щербаков Максим')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            //---------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Пасынков Александр')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Никулин Семен')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Павлов Леонид')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            //---------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Собенин Даниил')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Кривенко Даниил')->first()->id,
                'number' => null,
                'penalties' => 0,
                'assists' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Кошелев Александр')->first()->id,
                'number' => null,
                'number' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            //---------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Сон Александр')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Ардашев Дмитрий')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Ардашев Кирилл')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties'=>0,
                'matches' => 0,
            ],
            //---------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Сорокин Артем')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Ершов Иван')->first()->id,
                'number' => null,
                'goals' => 0,
                'assists' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Данилов Иван')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            //---------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Бондырев Игорь')->first()->id,
                'number' => null,
                'number' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Кривенко Артем')->first()->id,
                'number' => null,
                'goals' => 0,
                'number' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Веселовский Роман')->first()->id,
                'number' => null,
                'assists' => 0,
                'goals' => 0,
                'penalties' => 0,
                'matches' => 0,
            ],
            //---------------------------------------
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Ахметов Тимур')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Стручинский Виктор')->first()->id,
                'number' => null,
                'number' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Ухарский Андрей')->first()->id,
                'number' => null,
                'number' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Пасечник Никита')->first()->id,
                'number' => null,
                'number' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Величко Глеб')->first()->id,
                'number' => null,
                'assists' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
            ],
            [
                'championship_id' => $zo,
                'team_id' => $zubr,
                'player_id' => Player::where('full_name', 'Кузнецов Даниил')->first()->id,
                'number' => null,
                'number' => 0,
                'penalties' => 0,
                'goals' => 0,
                'matches' => 0,
                'gaa'=>0,
            ],
        ];

        // $vympelvPlayers = [
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Шарпанов Виктор')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 0,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Бардин Даниил')->first()->id,
        //         'number' => 55,
        //         'assists' => 2,
        //         'penalties' => 5,
        //         'goals' => 1,
        //         'matches' => 6,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Кокарев Александр')->first()->id,
        //         'number' => 23,
        //         'assists' => 2,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        //     //-----------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Пульников Илья')->first()->id,
        //         'number' => 38,
        //         'assists' => 1,
        //         'penalties' => 1,
        //         'goals' => 1,
        //         'matches' => 5,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Грибков Илья')->first()->id,
        //         'number' => 36,
        //         'assists' => 1,
        //         'penalties' => 0,
        //         'goals' => 1,
        //         'matches' => 5,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Фролов Матвей')->first()->id,
        //         'number' => 81,
        //         'assists' => 2,
        //         'penalties' => 0,
        //         'goals' => 4,
        //         'matches' => 4,
        //     ],
        //     //-----------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Петров Илья')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Лебедев Александр')->first()->id,
        //         'number' => 23,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Лысых Илья')->first()->id,
        //         'number' => 48,
        //         'assists' => 2,
        //         'penalties' => 2,
        //         'goals' => 4,
        //         'matches' => 5,
        //     ],
        //     //-----------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Лямин Семен')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Белоусов Анатолий')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Бычков Егор')->first()->id,
        //         'number' => 57,
        //         'number' => 0,
        //         'penalties' => 2,
        //         'goals' => 1,
        //         'matches' => 5,
        //     ],
        //     //-----------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Волохов Александр')->first()->id,
        //         'number' => 59,
        //         'assists' => 3,
        //         'penalties' => 0,
        //         'goals' => 2,
        //         'matches' => 5,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Игнатьев Кирилл')->first()->id,
        //         'number' => 52,
        //         'assists' => 1,
        //         'penalties' => 0,
        //         'goals' => 2,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Сагимбаев Мерген')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     //-----------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Смирнов Даниил')->first()->id,
        //         'number' => 76,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 1,
        //         'matches' => 2,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Тельцов Иван')->first()->id,
        //         'number' => 96,
        //         'assists' => 3,
        //         'penalties' => 0,
        //         'goals' => 2,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Тимофеев Дмитрий')->first()->id,
        //         'number' => 80,
        //         'assists' => 6,
        //         'penalties' => 0,
        //         'goals' => 10,
        //         'matches' => 5,
        //     ],
        //     //-----------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Уткин Дмитрий')->first()->id,
        //         'number' => 44,
        //         'assists' => 5,
        //         'penalties' => 0,
        //         'goals' => 2,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Шайтанов Александр')->first()->id,
        //         'number' => 32,
        //         'assists' => 1,
        //         'penalties' => 3,
        //         'goals' => 0,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Свешников Вячеслав')->first()->id,
        //         'number' => 93,
        //         'assists' => 1,
        //         'penalties' => 0,
        //         'goals' => 2,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Кардышев Владислав')->first()->id,
        //         'number' => 2,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 1,
        //         'gaa'=>3,
        //     ],
        // ];

        $vympelvPlayers = [
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Шарпанов Виктор')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Бардин Даниил')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Кокарев Александр')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Пульников Илья')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Грибков Илья')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Фролов Матвей')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Петров Илья')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Лебедев Александр')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Лысых Илья')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Лямин Семен')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Белоусов Анатолий')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Бычков Егор')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Волохов Александр')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Игнатьев Кирилл')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Сагимбаев Мерген')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Смирнов Даниил')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Тельцов Иван')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Тимофеев Дмитрий')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Уткин Дмитрий')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Шайтанов Александр')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Свешников Вячеслав')->first()->id,
            'number' => 0,
            'assists' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
        ],
        [
            'championship_id' => $zo,
            'team_id' => $vympelV,
            'player_id' => Player::where('full_name', 'Кардышев Владислав')->first()->id,
            'number' => 0,
            'penalties' => 0,
            'goals' => 0,
            'matches' => 0,
            'gaa' => 0,
        ],
    ];


        // $yaroslavichPlayers = [
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Созонов Юрий')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 4,
        //         'gaa'=>3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Тихонов Ярослав')->first()->id,
        //         'number' => 33,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 5,
        //         'gaa'=>8,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Шведов Константин')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     //--------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Паутов Александр')->first()->id,
        //         'number' => null,
        //         'assists' => 2,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Сарычев Никита')->first()->id,
        //         'number' => 42,
        //         'assists' => 1,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Ященин Савелий')->first()->id,
        //         'number' => 44,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Красильников Георгий')->first()->id,
        //         'number' => 45,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 2,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Вельс Григорий')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     //--------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Клёмин Владимир')->first()->id,
        //         'number' => 63,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Чумаков Архип')->first()->id,
        //         'number' => 68,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 0,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Товстый Александр')->first()->id,
        //         'number' => 28,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 4,
        //     ],
        //     //--------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Зашивалов Даниил')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 1,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Нежданов Игорь')->first()->id,
        //         'number' => 29,
        //         'assists'=> 1,
        //         'penalties' => 0,
        //         'goals' => 1,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Золотов Тихан')->first()->id,
        //         'number' => 31,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     //--------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Шилов Никита')->first()->id,
        //         'number' => 39,
        //         'assists'=> 2,
        //         'penalties' => 0,
        //         'goals' => 5,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Афанасьев Артем')->first()->id,
        //         'number' => 67,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Левченко Владислав')->first()->id,
        //         'number' => 77,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 4,
        //     ],
        //     //--------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Федотов Георгий')->first()->id,
        //         'number' => 88,
        //         'assists' => 5,
        //         'penalties' => 0,
        //         'goals' => 2,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Воронин Тимофей')->first()->id,
        //         'number' => 91,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 0,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Смирнов Илья')->first()->id,
        //         'number' => 94,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 2,
        //     ],
        //     //--------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Зубов Матвей')->first()->id,
        //         'number' => 99,
        //         'goals' => 5,
        //         'assists' => 2,
        //         'penalties' => 2,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $yaroslavich,
        //         'player_id' => Player::where('full_name', 'Божедомов Михаил')->first()->id,
        //         'number' => 34,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],

        // ];
$yaroslavichPlayers = [
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Созонов Юрий')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
        'gaa' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Тихонов Ярослав')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
        'gaa' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Шведов Константин')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Паутов Александр')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Сарычев Никита')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Ященин Савелий')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Красильников Георгий')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Вельс Григорий')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Клёмин Владимир')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Чумаков Архип')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Товстый Александр')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Зашивалов Даниил')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Нежданов Игорь')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Золотов Тихан')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Шилов Никита')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Афанасьев Артем')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Левченко Владислав')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Федотов Георгий')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Воронин Тимофей')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Смирнов Илья')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Зубов Матвей')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $yaroslavich,
        'player_id' => Player::where('full_name', 'Божедомов Михаил')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
];

        // $torpedoPlayers = [
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Чеблоков Даниил')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Тихонов Антон')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Тумаков Иван')->first()->id,
        //         'number' => 35,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 2,
        //         'gaa' => 9
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Пеньков Никита')->first()->id,
        //         'number' => 31,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 2,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Казаков Даниил')->first()->id,
        //         'number' => 88,
        //         'assists' => 1,
        //         'penalties' => 2,
        //         'goals' => 1,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Зазнобин Егор')->first()->id,
        //         'number' => 71,
        //         'assists' => 1,
        //         'penalties' => 3,
        //         'goals' => 0,
        //         'matches' => 5,
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Челин Павел')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Голубев Владимир')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Иванов Тихон')->first()->id,
        //         'number' => 95,
        //         'assists' => 2,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 4,
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Кравчук Егор')->first()->id,
        //         'number' => 73,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Белавский Дмитрий')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Ткаченко Никита')->first()->id,
        //         'number' => 97,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 2,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Крюков Даниил')->first()->id,
        //         'number' => null,
        //         'assists' => 1,
        //         'penalties' => 1,
        //         'goals' => 2,
        //         'matches' => 4,
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Марков Андрей')->first()->id,
        //         'number' => 79,
        //         'assists' => 2,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Морозов Иван')->first()->id,
        //         'number' => 27,
        //         'number' => 0,
        //         'penalties' => 2,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Медведев Георгий')->first()->id,
        //         'number' => 8,
        //         'assists' => 1,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 2,
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Шушин Даниил')->first()->id,
        //         'number' => 96,
        //         'assists' => 1,
        //         'penalties' => 0,
        //         'goals' => 4,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Шлыков Егор')->first()->id,
        //         'number' => 97,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 1,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Седов Егор')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Железняков Мирослав')->first()->id,
        //         'number' => 7,
        //         'assists' => 1,
        //         'penalties' => 0,
        //         'goals' => 3,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Камушков Клим')->first()->id,
        //         'number' => 2,
        //         'assists' => 2,
        //         'penalties' => 1,
        //         'goals' => 1,
        //         'matches' => 5,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Савченко Павел')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Заблоцкий Евгений')->first()->id,
        //         'number' => 7,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 1,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Тельман Евгений')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Чванчиков Андрей')->first()->id,
        //         'number' => 9,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 3,
        //         'matches' => 3,
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Кустов Даниил')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Орлов Илья')->first()->id,
        //         'number' => 96,
        //         'assists' => 2,
        //         'penalties' => 0,
        //         'goals' => 2,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Кулешов Владислав')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     //-------------------------------------
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Воробьев Владислав')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 3,
        //         'matches' => 4,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Малетин Илья')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Пятаков Алексей')->first()->id,
        //         'number' => 98,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 1,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Жилов Сергей')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 2,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Таганчиков Сергей')->first()->id,
        //         'number' => 86,
        //         'assists' => 4,
        //         'penalties' => 1,
        //         'goals' => 0,
        //         'matches' => 3,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Трунов Сергей')->first()->id,
        //         'number' => 2,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Идрисов Камиль')->first()->id,
        //         'number' => 27,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        // ];

        // $otherPlayer = [
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Рачев Кирилл')->first()->id,
        //         'number' => null,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $vympelV,
        //         'player_id' => Player::where('full_name', 'Воробьев Матвей')->first()->id,
        //         'number' => 78,
        //         'number' => 0,
        //         'penalties' => 1,
        //         'goals' => 0,
        //         'matches' => 1,
        //     ],
        //     [
        //         'championship_id' => $zo,
        //         'team_id' => $torpedo,
        //         'player_id' => Player::where('full_name', 'Киселев Никита')->first()->id,
        //         'number' => 0,
        //         'number' => 0,
        //         'penalties' => 0,
        //         'goals' => 0,
        //         'matches' => 0,
        //     ],
        // ];
        $torpedoPlayers = [
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Чеблоков Даниил')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Тихонов Антон')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Тумаков Иван')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
        'gaa' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Пеньков Никита')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Казаков Даниил')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Зазнобин Егор')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Челин Павел')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Голубев Владимир')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Иванов Тихон')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Кравчук Егор')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Белавский Дмитрий')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Ткаченко Никита')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Крюков Даниил')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Марков Андрей')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Морозов Иван')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Медведев Георгий')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Шушин Даниил')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Шлыков Егор')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Седов Егор')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Железняков Мирослав')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Камушков Клим')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Савченко Павел')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Заблоцкий Евгений')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Тельман Евгений')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Чванчиков Андрей')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Кустов Даниил')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Орлов Илья')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Кулешов Владислав')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Воробьев Владислав')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Малетин Илья')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Пятаков Алексей')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Жилов Сергей')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Таганчиков Сергей')->first()->id,
        'number' => 0,
        'assists' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Трунов Сергей')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Идрисов Камиль')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
];

$otherPlayer = [
    [
        'championship_id' => $zo,
        'team_id' => $vympelV,
        'player_id' => Player::where('full_name', 'Рачев Кирилл')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $vympelV,
        'player_id' => Player::where('full_name', 'Воробьев Матвей')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
    [
        'championship_id' => $zo,
        'team_id' => $torpedo,
        'player_id' => Player::where('full_name', 'Киселев Никита')->first()->id,
        'number' => 0,
        'penalties' => 0,
        'goals' => 0,
        'matches' => 0,
    ],
];


        foreach ($championshipGames as $game) {
            ChampionshipGame::create($game);
        }
        echo "\n✅ Связь матчей с чемпионатом настроена.\n\n";

        foreach ($teams as $team) {
            ChampionshipTeam::create($team);
        }
        echo "✅ Связь матчей с командами настроена.\n\n";

        foreach ($pereslavlPlayers as $player) {
            ChampionshipPlayer::create($player);
        }
        echo "✅ Команда Переславль заполнена.\n\n";

        foreach ($zubrPlayers as $player) {
            ChampionshipPlayer::create($player);
        }
        echo "✅ Команда Зубр заполнена.\n\n";

        foreach ($vympelvPlayers as $player) {
            ChampionshipPlayer::create($player);
        }
        echo "✅ Команда Вымпел-V заполнена.\n\n";

        foreach ($yaroslavichPlayers as $player) {
            ChampionshipPlayer::create($player);
        }
        echo "✅ Команда Ярославич заполнена.\n\n";

        foreach ($torpedoPlayers as $player) {
            ChampionshipPlayer::create($player);
        }
        echo "✅ Команда Торпедо заполнена.\n\n";

        foreach ($otherPlayer as $player) {
            ChampionshipPlayer::create($player);
        }
        echo "✅ Дополнительные игроки заполнены\n\n";
    }
}
