"""update models

Revision ID: 4e7cdfec0238
Revises: baea9ef7ead4
Create Date: 2025-11-04 10:56:43.701492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7cdfec0238'
down_revision: Union[str, None] = 'baea9ef7ead4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_championship_game', 'championship_games', ['championship_id', 'game_id'])
    op.create_unique_constraint('uq_championship_team_player', 'championship_players', ['championship_id', 'team_id', 'player_id'])
    op.create_unique_constraint('uq_championship_team', 'championship_teams', ['championship_id', 'team_id'])
    op.create_unique_constraint('uq_tournament_game', 'tournament_games', ['tournament_id', 'game_id'])
    op.create_unique_constraint('uq_tournament_team_player', 'tournament_players', ['tournament_id', 'team_id', 'player_id'])
    op.create_unique_constraint('uq_tournament_team', 'tournament_teams', ['tournament_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tournament_team', 'tournament_teams', type_='unique')
    op.drop_constraint('uq_tournament_team_player', 'tournament_players', type_='unique')
    op.drop_constraint('uq_tournament_game', 'tournament_games', type_='unique')
    op.drop_constraint('uq_championship_team', 'championship_teams', type_='unique')
    op.drop_constraint('uq_championship_team_player', 'championship_players', type_='unique')
    op.drop_constraint('uq_championship_game', 'championship_games', type_='unique')
    # ### end Alembic commands ###
