"""add video_url

Revision ID: 5bf029e17780
Revises: 2f5c687afd31
Create Date: 2025-11-24 15:49:52.037206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf029e17780'
down_revision: Union[str, None] = '2f5c687afd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'video_url')
    # ### end Alembic commands ###
