"""«add points

Revision ID: 84a4991b1c73
Revises: c34880d01362
Create Date: 2025-11-06 13:26:06.095649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a4991b1c73'
down_revision: Union[str, None] = 'c34880d01362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('championship_teams', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('tournament_teams', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_teams', 'points')
    op.drop_column('championship_teams', 'points')
    # ### end Alembic commands ###
