"""add role for admin

Revision ID: 94beff355750
Revises: 5bf029e17780
Create Date: 2025-11-26 08:23:44.174228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94beff355750'
down_revision: Union[str, None] = '5bf029e17780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'role')
    # ### end Alembic commands ###
