"""add contract field to championship and tournament players

Revision ID: a1b2c3d4e5f
Revises: edaf01dc7b70
Create Date: 2025-03-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f'
down_revision: Union[str, None] = '3f2c6f9a1a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('championship_players', sa.Column('contract', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tournament_players', sa.Column('contract', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_players', 'contract')
    op.drop_column('championship_players', 'contract')
    # ### end Alembic commands ###
