"""initial

Revision ID: baea9ef7ead4
Revises: 
Create Date: 2025-11-03 14:41:36.591319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baea9ef7ead4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('championships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championships_id'), 'championships', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('grip', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('players_count', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('championship_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('gaa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championship_players_id'), 'championship_players', ['id'], unique=False)
    op.create_table('championship_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('extra_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championship_teams_id'), 'championship_teams', ['id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('score_team_a', sa.Integer(), nullable=True),
    sa.Column('score_team_b', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('bullet_win_team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bullet_win_team'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('tournament_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('gaa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_players_id'), 'tournament_players', ['id'], unique=False)
    op.create_table('tournament_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('extra_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_teams_id'), 'tournament_teams', ['id'], unique=False)
    op.create_table('championship_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('championship_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championship_games_id'), 'championship_games', ['id'], unique=False)
    op.create_table('tournament_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_games_id'), 'tournament_games', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_games_id'), table_name='tournament_games')
    op.drop_table('tournament_games')
    op.drop_index(op.f('ix_championship_games_id'), table_name='championship_games')
    op.drop_table('championship_games')
    op.drop_index(op.f('ix_tournament_teams_id'), table_name='tournament_teams')
    op.drop_table('tournament_teams')
    op.drop_index(op.f('ix_tournament_players_id'), table_name='tournament_players')
    op.drop_table('tournament_players')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_championship_teams_id'), table_name='championship_teams')
    op.drop_table('championship_teams')
    op.drop_index(op.f('ix_championship_players_id'), table_name='championship_players')
    op.drop_table('championship_players')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_championships_id'), table_name='championships')
    op.drop_table('championships')
    # ### end Alembic commands ###
