"""update_user_profile

Revision ID: d07009222e6d
Revises: 5ececea04d3f
Create Date: 2025-09-10 10:41:25.025928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d07009222e6d"
down_revision: Union[str, None] = "5ececea04d3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_profiles", "avatar_media_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_profiles", "avatar_media_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
